version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: nimbus-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - nimbus_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nimbus
      POSTGRES_USER: nimbus_user
      POSTGRES_PASSWORD: nimbus_pass

  vault:
    image: hashicorp/vault:1.21.1
    container_name: nimbus-vault
    restart: always
    ports:
      - "8200:8200"
    volumes:
      - nimbus_vault_data:/vault/file
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server -dev -dev-root-token-id=root-token -dev-listen-address=0.0.0.0:8200"

  redis:
    image: redis:8.4.0-alpine
    container_name: nimbus-redis
    ports: [ "6379:6379" ]

  redis-insight:
    image: redis/redisinsight:2.70
    container_name: nimbus-redis-insight
    ports: [ "5540:5540" ]
    depends_on: [ redis ]


volumes:
  nimbus_pg_data:
  nimbus_vault_data:
